parameters:
  coverageParam: ''

steps:
  - powershell: |
        Invoke-WebRequest -Uri "https://github.com/Azure/azure-sdk-tools/releases/download/sdk-tools_14793/sdk-tools.zip" `
        -OutFile "sdk-tools.zip" | Wait-Process; Expand-Archive -Path "sdk-tools.zip" -DestinationPath "./sdk-tools/"
    workingDirectory: '$(Build.BinariesDirectory)'
    displayName: 'Download Tools Archive From Github Release and Extract it'

  - task: UsePythonVersion@0
    displayName: 'Use Python $(PythonVersion)'
    inputs:
      versionSpec: '$(PythonVersion)'

  - bash: printenv
    displayName: Show environment variables

  - bash: |
      export PIP_CACHE_DIR="~/.cache/pip"
      echo "##vso[task.setvariable variable=PIP_CACHE_DIR]$PIP_CACHE_DIR"
      mkdir -p $PIP_CACHE_DIR
    displayName: Set pip cache folder
    continueOnError: true

  - task: DownloadPipelineArtifact@1
    inputs:
      targetPath: $(PIP_CACHE_DIR)
      artifactName: $(cacheName)
      buildType: specific
      buildVersionToDownload: specific
      pipelineId: 53
    condition: eq(variables['restoreCache'], 'true')
    displayName: 'Restore cache'
    continueOnError: true

  - task: PythonScript@0
    displayName: 'Run VerifyAgentOS script'
    inputs:
      scriptPath: '$(Build.BinariesDirectory)/sdk-tools/scripts/python/verify_agent_os.py'
      arguments: $(OSName)

  - script: |
      pip install pathlib twine codecov beautifulsoup4
    displayName: 'Prep Environment'

  - task: PythonScript@0
    displayName: 'Setup and Run Tests'
    inputs:
      scriptPath: 'scripts/devops_tasks/setup_execute_tests.py'
      arguments: '"$(BuildTargetingString)" --junitxml="junit/test-results.xml" ${{ parameters.coverageParam }}'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: $(cacheName)
      targetPath: $(PIP_CACHE_DIR)
    condition: ne(variables['restoreCache'], 'true')
    displayName: 'Save cache'
    continueOnError: true

 # - task: PublishTestResults@2
 #   condition: succeededOrFailed()
 #   inputs:
 #     testResultsFiles: 'junit/test-results.xml'
 #     testRunTitle: '$(OSName) Python $(PythonVersion)'